### ISSUE TITLE
Adding run-time folder to library path causes an issue

### ISSUE THREAD

**Issue by EminBorbor** [500Foods/TMS-WEB-Core-JSExtend#2]
Hi Andrew, I am creating my first component..
After adding run-time folder to library path causes compiler error. It overrides/forgets TMS library paths.
[Error] JSFlatPickr.pas(15): identifier not found "TWebCustomControl"
So I am stick with the first option, adding runtime unit to my project directly.

**Comment by 500Foods** [comment]
If you have time/interest to tinker with it, try changing the reference from TWebCustomControl to just TCustomControl in the runtime version.  I seem to vaguely recall that being an issue at the outset.  But having it as a file in the project made it super-easy to edit it along with a test project, so I never went back to the library method. I don't think it's forgetting the other paths, just that it doesn't know where to get TWebCustomControl.  Probably also addressable by adding something to units but not sure offhand which unit.... This was my first time creating a component so LOTS of learning to be had! I will investigate further though.

**Comment by EminBorbor** [comment]
You are right. Also copying the runtime unit into TMS core source folder does not help. I will be adding runtime units to my projects for now.
